import Foundation
import Libgit2Module

/// LibGit error domain name
public let libGit2ErrorDomain = "org.libgit2.libgit2"

extension NSError {
    /// Returns an NSError with an error domain and message for libgit2 errors.
    ///
    /// :param: errorCode An error code returned by a libgit2 function.
    /// :param: libGit2PointOfFailure The name of the libgit2 function that produced the
    ///         error code.
    /// :returns: An NSError with a libgit2 error domain, code, and message.
    convenience init(
        gitError errorCode: Int32,
        pointOfFailure: String? = nil,
        suggestionsFix: [String]? = nil
    ) {
        let code = Int(errorCode)
        var userInfo: [String: String] = [:]

        if let message = errorMessage(errorCode) {
            userInfo[NSLocalizedDescriptionKey] = message
        } else {
            userInfo[NSLocalizedDescriptionKey] = "Unknown libgit2 error."
        }

        if let pointOfFailure {
            userInfo[NSLocalizedFailureReasonErrorKey] = "\(pointOfFailure) failed."
        }

        if let suggestionsFix {
            userInfo[NSLocalizedRecoverySuggestionErrorKey] = suggestionsFix.joined(separator: ", ")
        }

        self.init(domain: libGit2ErrorDomain, code: code, userInfo: userInfo)
    }
}

/// The Git information
public enum Git {
    /// The git version
    /// - Returns: the `String` version
    public static func version() -> String {
        let major = UnsafeMutablePointer<Int32>.allocate(capacity: 1)
        let minor = UnsafeMutablePointer<Int32>.allocate(capacity: 1)
        let rev = UnsafeMutablePointer<Int32>.allocate(capacity: 1)

        defer { [major, minor, rev].forEach { $0.deallocate() } }
        git_libgit2_version(major, minor, rev)
        return [major, minor, rev].compactMap { "\($0.pointee)" }.joined(separator: ".")
    }
}

/// Returns the libgit2 error message for the given error code.
///
/// The error message represents the last error message generated by
/// libgit2 in the current thread.
///
/// :param: errorCode An error code returned by a libgit2 function.
/// :returns: If the error message exists either in libgit2's thread-specific registry,
///           or errno has been set by the system, this function returns the
///           corresponding string representation of that error. Otherwise, it returns
///           nil.
func errorMessage(_ errorCode: Int32) -> String? {
    let last = git_error_last()
    if let lastErrorPointer = last {
        return String(validatingCString: lastErrorPointer.pointee.message)
    } else if Int32(errorCode) == GIT_ERROR_OS.rawValue {
        return String(validatingCString: strerror(errno))
    } else {
        return nil
    }
}

func remoteCallbacks(credentials: Credentials) -> git_remote_callbacks {
    let pointer = UnsafeMutablePointer<git_remote_callbacks>.allocate(capacity: 1)
    git_remote_init_callbacks(pointer, UInt32(GIT_REMOTE_CALLBACKS_VERSION))

    var options = pointer.move()

    options.payload = credentials.toPointer()
    options.credentials = credentialsCallback

    return options
}

func fetchOptions(credentials: Credentials, proxy: ProxyConfiguration?) -> git_fetch_options {
    let pointer = UnsafeMutablePointer<git_fetch_options>.allocate(capacity: 1)
    git_fetch_options_init(pointer, UInt32(GIT_FETCH_OPTIONS_VERSION))

    var options = pointer.move()

    pointer.deallocate()

    options.callbacks.payload = credentials.toPointer()
    options.callbacks.credentials = credentialsCallback
    options.proxy_opts = proxyOptions(proxy: proxy)

    return options
}

func printMatchedCBCallback(
    url: UnsafePointer<CChar>?,
    pathspec path: UnsafePointer<CChar>?,
    payload: UnsafeMutableRawPointer?
) -> Int32 {
    var result: Int32 = 0
    let statusBuffer = UnsafeMutablePointer<UInt32>.allocate(capacity: 1)
    var status = statusBuffer.move()
    statusBuffer.deallocate()

    let repository = Repository.fromPointer(payload!)

    let resultStatus = git_status_file(&status, repository.pointer, url)
    guard resultStatus == GIT_OK.rawValue else {
        print(errorMessage(result)!)
        print("error: git_status_file")
        return result
    }

    if ((status & GIT_STATUS_WT_MODIFIED.rawValue) != 0) || ((status & GIT_STATUS_WT_NEW.rawValue) != 0) {
        print("add \(String(cString: path!))\n")
        result = 1
    } else if (status & GIT_STATUS_WT_DELETED.rawValue) != 0 {
        print("removed \(String(cString: path!))\n")
        result = 1
    } else {
        result = 1
    }

    return result
}

/// Helper function used as the libgit2 progress callback in git_checkout_options.
/// This is a function with a type signature of git_checkout_progress_cb.
func checkoutProgressCallback(
    path: UnsafePointer<Int8>?,
    completedSteps: Int,
    totalSteps: Int,
    payload: UnsafeMutableRawPointer?
) {
    if let payload {
        let buffer = payload.assumingMemoryBound(to: CheckoutProgressBlock.self)
        let block: CheckoutProgressBlock
        if completedSteps < totalSteps {
            block = buffer.pointee
        } else {
            block = buffer.move()
            buffer.deallocate()
        }
        block(path.flatMap(String.init(validatingCString:)), completedSteps, totalSteps)
    }
}

/// Helper function for initializing libgit2 git_checkout_options.
///
/// :param: strategy The strategy to be used when checking out the repo, see CheckoutStrategy
/// :param: progress A block that's called with the progress of the checkout.
/// :returns: Returns a git_checkout_options struct with the progress members set.
func checkoutOptions(
    strategy: CheckoutStrategy,
    progress: CheckoutProgressBlock? = nil
) -> git_checkout_options {
    // Do this because GIT_CHECKOUT_OPTIONS_INIT is unavailable in swift
    let pointer = UnsafeMutablePointer<git_checkout_options>.allocate(capacity: 1)
    git_checkout_options_init(pointer, UInt32(GIT_CHECKOUT_OPTIONS_VERSION))
    var options = pointer.move()
    pointer.deallocate()

    options.checkout_strategy = strategy.gitCheckoutStrategy.rawValue

    if progress != nil {
        options.progress_cb = checkoutProgressCallback
        let blockPointer = UnsafeMutablePointer<CheckoutProgressBlock>.allocate(capacity: 1)
        blockPointer.initialize(to: progress!)
        options.progress_payload = UnsafeMutableRawPointer(blockPointer)
    }

    return options
}

func pushOptions(credentials: Credentials, proxy: ProxyConfiguration? = nil) -> git_push_options {
    let pointer = UnsafeMutablePointer<git_push_options>.allocate(capacity: 1)
    git_push_options_init(pointer, UInt32(GIT_PUSH_OPTIONS_VERSION))

    var options = pointer.move()

    pointer.deallocate()

    options.callbacks.payload = credentials.toPointer()
    options.callbacks.credentials = credentialsCallback
    options.proxy_opts = proxyOptions(proxy: proxy)

    return options
}

func proxyOptions(proxy: ProxyConfiguration? = nil) -> git_proxy_options {
    let gitProxyType: git_proxy_t = proxy?.url == nil ? GIT_PROXY_AUTO : GIT_PROXY_SPECIFIED
    let cURL = proxy?.url?.absoluteString.cString
    let payload = ProxyCredential(
        username: proxy?.credential?.username,
        password: proxy?.credential?.password
    )
    return .init(
        version: UInt32(GIT_PROXY_OPTIONS_VERSION),
        type: gitProxyType,
        url: cURL,
        credentials: credentialsProxyCallback,
        certificate_check: certificateCheckProxyCallback,
        payload: payload.toPointer()
    )
}

func cloneOptions(
    bare: Bool = false,
    localClone: Bool = false,
    fetchOptions: git_fetch_options? = nil,
    checkoutOptions: git_checkout_options? = nil
) -> git_clone_options {
    let pointer = UnsafeMutablePointer<git_clone_options>.allocate(capacity: 1)
    git_clone_options_init(pointer, UInt32(GIT_CLONE_OPTIONS_VERSION))

    var options = pointer.move()

    pointer.deallocate()

    options.bare = bare ? 1 : 0

    if localClone {
        options.local = GIT_CLONE_NO_LOCAL
    }

    if let checkoutOptions {
        options.checkout_opts = checkoutOptions
    }

    if let fetchOptions {
        options.fetch_opts = fetchOptions
    }

    return options
}

extension Array {
    func aggregateResult<Value, Error>() -> Result<[Value], Error> where Element == Result<
        Value,
        Error
    > {
        var values: [Value] = []
        for result in self {
            switch result {
            case let .success(value):
                values.append(value)
            case let .failure(error):
                return .failure(error)
            }
        }
        return .success(values)
    }
}

func resolveUrl(
    urlResolved _: UnsafeMutablePointer<OpaquePointer?>,
    url _: UnsafePointer<CChar>,
    payload _: UnsafeMutableRawPointer
) -> Int32 {
    GIT_OK.rawValue
}
