import Foundation
import Libgit2Module

// swiftlint:disable file_length
/// LibGit error domain name
public let libGit2ErrorDomain = "org.libgit2.libgit2"

extension NSError {
    /// Returns an NSError with an error domain and message for libgit2 errors.
    ///
    /// :param: errorCode An error code returned by a libgit2 function.
    /// :param: libGit2PointOfFailure The name of the libgit2 function that produced the
    ///         error code.
    /// :returns: An NSError with a libgit2 error domain, code, and message.
    convenience init(
        gitError errorCode: Int32,
        pointOfFailure: String? = nil,
        suggestionsFix: [String]? = nil
    ) {
        let code = Int(errorCode)
        var userInfo: [String: String] = [:]

        if let message = errorMessage(errorCode) {
            userInfo[NSLocalizedDescriptionKey] = message
        } else {
            userInfo[NSLocalizedDescriptionKey] = "Unknown libgit2 error."
        }

        if let pointOfFailure {
            userInfo[NSLocalizedFailureReasonErrorKey] = "\(pointOfFailure) failed."
        }

        if let suggestionsFix {
            userInfo[NSLocalizedRecoverySuggestionErrorKey] = suggestionsFix.joined(separator: ", ")
        }

        self.init(domain: libGit2ErrorDomain, code: code, userInfo: userInfo)
    }
}

/// The Git information
public enum Git {
    /// The git version
    /// - Returns: the `String` version
    public static func version() -> String {
        let major = UnsafeMutablePointer<Int32>.allocate(capacity: 1)
        let minor = UnsafeMutablePointer<Int32>.allocate(capacity: 1)
        let rev = UnsafeMutablePointer<Int32>.allocate(capacity: 1)

        defer { [major, minor, rev].forEach { $0.deallocate() } }
        git_libgit2_version(major, minor, rev)
        return [major, minor, rev].compactMap { "\($0.pointee)" }.joined(separator: ".")
    }
}

/// Returns the libgit2 error message for the given error code.
///
/// The error message represents the last error message generated by
/// libgit2 in the current thread.
///
/// :param: errorCode An error code returned by a libgit2 function.
/// :returns: If the error message exists either in libgit2's thread-specific registry,
///           or errno has been set by the system, this function returns the
///           corresponding string representation of that error. Otherwise, it returns
///           nil.
func errorMessage(_ errorCode: Int32) -> String? {
    let last = git_error_last()
    if let lastErrorPointer = last {
        return String(validatingCString: lastErrorPointer.pointee.message)
    } else if Int32(errorCode) == GIT_ERROR_OS.rawValue {
        return String(validatingCString: strerror(errno))
    } else {
        return nil
    }
}

func remoteCallbacks(credentials: Credentials) -> git_remote_callbacks {
    let pointer = UnsafeMutablePointer<git_remote_callbacks>.allocate(capacity: 1)
    git_remote_init_callbacks(pointer, UInt32(GIT_REMOTE_CALLBACKS_VERSION))

    var options = pointer.move()

    options.payload = credentials.toPointer()
    options.credentials = credentialsCallback

    return options
}

func fetchOptions(credentials: Credentials, proxy: ProxyConfiguration?) -> git_fetch_options {
    let pointer = UnsafeMutablePointer<git_fetch_options>.allocate(capacity: 1)
    git_fetch_options_init(pointer, UInt32(GIT_FETCH_OPTIONS_VERSION))

    var options = pointer.move()

    pointer.deallocate()

    options.callbacks.payload = credentials.toPointer()
    options.callbacks.credentials = credentialsCallback
    options.proxy_opts = proxyOptions(proxy: proxy)

    return options
}

func printMatchedCBCallback(
    url: UnsafePointer<CChar>?,
    pathspec path: UnsafePointer<CChar>?,
    payload: UnsafeMutableRawPointer?
) -> Int32 {
    var result: Int32 = 0
    let statusBuffer = UnsafeMutablePointer<UInt32>.allocate(capacity: 1)
    var status = statusBuffer.move()
    statusBuffer.deallocate()

    let repository = Repository.fromPointer(payload!)

    let resultStatus = git_status_file(&status, repository.pointer, url)
    guard resultStatus == GIT_OK.rawValue else {
        print(errorMessage(result)!)
        print("error: git_status_file")
        return result
    }

    if ((status & GIT_STATUS_WT_MODIFIED.rawValue) != 0) || ((status & GIT_STATUS_WT_NEW.rawValue) != 0) {
        print("add \(String(cString: path!))\n")
        result = 1
    } else if (status & GIT_STATUS_WT_DELETED.rawValue) != 0 {
        print("removed \(String(cString: path!))\n")
        result = 1
    } else {
        result = 1
    }

    return result
}

/// Helper function used as the libgit2 progress callback in git_checkout_options.
/// This is a function with a type signature of git_checkout_progress_cb.
private func checkoutProgressCallback(
    path: UnsafePointer<Int8>?,
    completedSteps: Int,
    totalSteps: Int,
    payload: UnsafeMutableRawPointer?
) {
    if let payload {
        let buffer = payload.assumingMemoryBound(to: CheckoutProgressBlock.self)
        let block: CheckoutProgressBlock
        if completedSteps < totalSteps {
            block = buffer.pointee
        } else {
            block = buffer.move()
            buffer.deallocate()
        }
        block(path.flatMap(String.init(validatingCString:)), completedSteps, totalSteps)
    }
}

/// Helper function for initializing libgit2 git_checkout_options.
///
/// :param: strategy The strategy to be used when checking out the repo, see CheckoutStrategy
/// :param: progress A block that's called with the progress of the checkout.
/// :returns: Returns a git_checkout_options struct with the progress members set.
private func checkoutOptions(
    strategy: CheckoutStrategy,
    progress: CheckoutProgressBlock? = nil
) -> git_checkout_options {
    // Do this because GIT_CHECKOUT_OPTIONS_INIT is unavailable in swift
    let pointer = UnsafeMutablePointer<git_checkout_options>.allocate(capacity: 1)
    git_checkout_options_init(pointer, UInt32(GIT_CHECKOUT_OPTIONS_VERSION))
    var options = pointer.move()
    pointer.deallocate()

    options.checkout_strategy = strategy.gitCheckoutStrategy.rawValue

    if progress != nil {
        options.progress_cb = checkoutProgressCallback
        let blockPointer = UnsafeMutablePointer<CheckoutProgressBlock>.allocate(capacity: 1)
        blockPointer.initialize(to: progress!)
        options.progress_payload = UnsafeMutableRawPointer(blockPointer)
    }

    return options
}

private func pushOptions(credentials: Credentials, proxy: ProxyConfiguration? = nil) -> git_push_options {
    let pointer = UnsafeMutablePointer<git_push_options>.allocate(capacity: 1)
    git_push_options_init(pointer, UInt32(GIT_PUSH_OPTIONS_VERSION))

    var options = pointer.move()

    pointer.deallocate()

    options.callbacks.payload = credentials.toPointer()
    options.callbacks.credentials = credentialsCallback
    options.proxy_opts = proxyOptions(proxy: proxy)

    return options
}

private func proxyOptions(proxy: ProxyConfiguration? = nil) -> git_proxy_options {
    let gitProxyType: git_proxy_t = proxy?.url == nil ? GIT_PROXY_AUTO : GIT_PROXY_SPECIFIED
    let cURL = proxy?.url?.absoluteString.cString
    let payload = ProxyCredential(
        username: proxy?.credential?.username,
        password: proxy?.credential?.password
    )
    return .init(
        version: UInt32(GIT_PROXY_OPTIONS_VERSION),
        type: gitProxyType,
        url: cURL,
        credentials: credentialsProxyCallback,
        certificate_check: certificateCheckProxyCallback,
        payload: payload.toPointer()
    )
}

private func cloneOptions(
    bare: Bool = false,
    localClone: Bool = false,
    fetchOptions: git_fetch_options? = nil,
    checkoutOptions: git_checkout_options? = nil
) -> git_clone_options {
    let pointer = UnsafeMutablePointer<git_clone_options>.allocate(capacity: 1)
    git_clone_options_init(pointer, UInt32(GIT_CLONE_OPTIONS_VERSION))

    var options = pointer.move()

    pointer.deallocate()

    options.bare = bare ? 1 : 0

    if localClone {
        options.local = GIT_CLONE_NO_LOCAL
    }

    if let checkoutOptions {
        options.checkout_opts = checkoutOptions
    }

    if let fetchOptions {
        options.fetch_opts = fetchOptions
    }

    return options
}

/// libgit2 requires a global initialization before most operations; Swift runs this once, lazily.
private let libgit2Initialization = git_libgit2_init()

/// A git repository.
/// Git `Repository` class
public final class Repository { // swiftlint:disable:this type_body_length
    // MARK: - Creating Repositories

    /// Create a new repository at the given URL.
    ///
    /// URL - The URL of the repository.
    ///
    /// Returns a `Result` with a `Repository` or an error.
    public static func create(at url: URL) -> Result<Repository, NSError> {
        var pointer: OpaquePointer?
        let result = url.withUnsafeFileSystemRepresentation {
            git_repository_init(&pointer, $0, 0)
        }

        guard result == GIT_OK.rawValue else {
            return Result.failure(NSError(gitError: result, pointOfFailure: "git_repository_init"))
        }

        let repository = Repository(pointer!)
        return Result.success(repository)
    }

    /// Load the repository at the given URL.
    ///
    /// URL - The URL of the repository.
    ///
    /// Returns a `Result` with a `Repository` or an error.
    public static func at(_ url: URL) -> Result<Repository, NSError> {
        var pointer: OpaquePointer?
        let result = url.withUnsafeFileSystemRepresentation {
            git_repository_open(&pointer, $0)
        }

        guard result == GIT_OK.rawValue else {
            return Result.failure(NSError(gitError: result, pointOfFailure: "git_repository_open"))
        }

        let repository = Repository(pointer!)
        return Result.success(repository)
    }

    /// Clone the repository from a given URL.
    ///
    /// remoteURL        - The URL of the remote repository
    /// localURL         - The URL to clone the remote repository into
    /// localClone       - Will not bypass the git-aware transport, even if remote is local.
    /// bare             - Clone remote as a bare repository.
    /// credentials      - Credentials to be used when connecting to the remote.
    /// checkoutStrategy - The checkout strategy to use, if being checked out.
    /// checkoutProgress - A block that's called with the progress of the checkout.
    /// proxy            - A proxy configuration
    ///
    /// Returns a `Result` with a `Repository` or an error.
    public static func clone(
        from remoteURL: URL,
        to localURL: URL,
        localClone: Bool = false,
        bare: Bool = false,
        credentials: Credentials = .default,
        checkoutStrategy: CheckoutStrategy = .Safe,
        proxy: ProxyConfiguration?,
        checkoutProgress: CheckoutProgressBlock? = nil
    ) -> Result<Repository, NSError> {
        _ = libgit2Initialization
        var options = cloneOptions(
            bare: bare,
            localClone: localClone,
            fetchOptions: fetchOptions(credentials: credentials, proxy: proxy),
            checkoutOptions: checkoutOptions(strategy: checkoutStrategy, progress: checkoutProgress)
        )

        var pointer: OpaquePointer?
        let remoteURLString = (remoteURL as NSURL).isFileReferenceURL() ? remoteURL.path : remoteURL
            .absoluteString
        let result = localURL.withUnsafeFileSystemRepresentation { localPath in
            git_clone(&pointer, remoteURLString, localPath, &options)
        }

        guard result == GIT_OK.rawValue else {
            return Result.failure(NSError(gitError: result, pointOfFailure: "git_clone"))
        }

        let repository = Repository(pointer!)
        return Result.success(repository)
    }

    // MARK: - Initializers

    /// Create an instance with a libgit2 `git_repository` object.
    ///
    /// The Repository assumes ownership of the `git_repository` object.
    public init(_ pointer: OpaquePointer) {
        git_libgit2_init()
        self.pointer = pointer

        let path = git_repository_workdir(pointer)
        self.directoryURL = path
            .map { URL(fileURLWithPath: String(validatingCString: $0)!, isDirectory: true) }
    }

    static func fromPointer(_ pointer: UnsafeMutableRawPointer) -> Repository {
        Unmanaged<Wrapper<Repository>>.fromOpaque(UnsafeRawPointer(pointer)).takeRetainedValue().value
    }

    deinit {
        git_repository_free(pointer)
        git_libgit2_shutdown()
    }

    // MARK: - Properties

    /// The underlying libgit2 `git_repository` object.
    public let pointer: OpaquePointer

    /// The URL of the repository's working directory, or `nil` if the
    /// repository is bare.
    public let directoryURL: URL?

    // MARK: - Object Lookups

    /// Load a libgit2 object and transform it to something else.
    ///
    /// oid       - The OID of the object to look up.
    /// type      - The type of the object to look up.
    /// transform - A function that takes the libgit2 object and transforms it
    ///             into something else.
    ///
    /// Returns the result of calling `transform` or an error if the object
    /// cannot be loaded.
    private func withGitObject<T>(
        _ oid: OID,
        type: git_object_t,
        transform: (OpaquePointer) -> Result<T, NSError>
    ) -> Result<T, NSError> {
        var pointer: OpaquePointer?
        var oid = oid.oid
        let result = git_object_lookup(&pointer, self.pointer, &oid, type)

        guard result == GIT_OK.rawValue else {
            return Result.failure(NSError(gitError: result, pointOfFailure: "git_object_lookup"))
        }

        let value = transform(pointer!)
        git_object_free(pointer)
        return value
    }

    private func withGitObject<T>(
        _ oid: OID,
        type: git_object_t,
        transform: (OpaquePointer) -> T
    ) -> Result<T, NSError> {
        withGitObject(oid, type: type) { Result.success(transform($0)) }
    }

    private func withGitObjects<T>(
        _ oids: [OID],
        type: git_object_t,
        transform: ([OpaquePointer]) -> Result<T, NSError>
    ) -> Result<T, NSError> {
        var pointers = [OpaquePointer]()
        defer {
            for pointer in pointers {
                git_object_free(pointer)
            }
        }

        for oid in oids {
            var pointer: OpaquePointer?
            var oid = oid.oid
            let result = git_object_lookup(&pointer, self.pointer, &oid, type)

            guard result == GIT_OK.rawValue else {
                return Result.failure(NSError(gitError: result, pointOfFailure: "git_object_lookup"))
            }

            pointers.append(pointer!)
        }

        return transform(pointers)
    }

    /// Loads the object with the given OID.
    ///
    /// oid - The OID of the blob to look up.
    ///
    /// Returns a `Blob`, `Commit`, `Tag`, or `Tree` if one exists, or an error.
    public func object(_ oid: OID) -> Result<ObjectType, NSError> {
        withGitObject(oid, type: GIT_OBJECT_ANY) { object in
            let type = git_object_type(object)
            if type == Blob.type {
                return Result.success(Blob(object))
            } else if type == Commit.type {
                return Result.success(Commit(object))
            } else if type == Tag.type {
                return Result.success(Tag(object))
            } else if type == Tree.type {
                return Result.success(Tree(object))
            }

            let error = NSError(
                domain: "org.libgit2.SwiftGit2",
                code: 1,
                userInfo: [
                    NSLocalizedDescriptionKey: "Unrecognized git_object_t '\(type)' for oid '\(oid)'."
                ]
            )
            return Result.failure(error)
        }
    }

    /// Loads the blob with the given OID.
    ///
    /// oid - The OID of the blob to look up.
    ///
    /// Returns the blob if it exists, or an error.
    public func blob(_ oid: OID) -> Result<Blob, NSError> {
        withGitObject(oid, type: GIT_OBJECT_BLOB) { Blob($0) }
    }

    /// Loads the commit with the given OID.
    ///
    /// oid - The OID of the commit to look up.
    ///
    /// Returns the commit if it exists, or an error.
    public func commit(_ oid: OID) -> Result<Commit, NSError> {
        withGitObject(oid, type: GIT_OBJECT_COMMIT) { Commit($0) }
    }

    /// Loads the tag with the given OID.
    ///
    /// oid - The OID of the tag to look up.
    ///
    /// Returns the tag if it exists, or an error.
    public func tag(_ oid: OID) -> Result<Tag, NSError> {
        withGitObject(oid, type: GIT_OBJECT_TAG) { Tag($0) }
    }

    /// Loads the tree with the given OID.
    ///
    /// oid - The OID of the tree to look up.
    ///
    /// Returns the tree if it exists, or an error.
    public func tree(_ oid: OID) -> Result<Tree, NSError> {
        withGitObject(oid, type: GIT_OBJECT_TREE) { Tree($0) }
    }

    /// Loads the referenced object from the pointer.
    ///
    /// pointer - A pointer to an object.
    ///
    /// Returns the object if it exists, or an error.
    public func object<T>(from pointer: PointerTo<T>) -> Result<T, NSError> {
        withGitObject(pointer.oid, type: pointer.type) { T($0) }
    }

    /// Loads the referenced object from the pointer.
    ///
    /// pointer - A pointer to an object.
    ///
    /// Returns the object if it exists, or an error.
    public func object(from pointer: Pointer) -> Result<ObjectType, NSError> {
        switch pointer {
        case let .blob(oid):
            blob(oid).map { $0 as ObjectType }
        case let .commit(oid):
            commit(oid).map { $0 as ObjectType }
        case let .tag(oid):
            tag(oid).map { $0 as ObjectType }
        case let .tree(oid):
            tree(oid).map { $0 as ObjectType }
        }
    }

    // MARK: - Remote Lookups

    /// Loads all the remotes in the repository.
    ///
    /// Returns an array of remotes, or an error.
    public func allRemotes() -> Result<[Remote], NSError> {
        let pointer = UnsafeMutablePointer<git_strarray>.allocate(capacity: 1)
        let result = git_remote_list(pointer, self.pointer)

        guard result == GIT_OK.rawValue else {
            pointer.deallocate()
            return Result.failure(NSError(gitError: result, pointOfFailure: "git_remote_list"))
        }

        let strarray = pointer.pointee
        let remotes: [Result<Remote, NSError>] = strarray.map {
            self.remote(named: $0)
        }
        git_strarray_dispose(pointer)
        pointer.deallocate()

        return remotes.aggregateResult()
    }

    private func remoteLookup<A>(named name: String, _ callback: (Result<OpaquePointer, NSError>) -> A) -> A {
        var pointer: OpaquePointer?
        defer { git_remote_free(pointer) }

        let result = git_remote_lookup(&pointer, self.pointer, name)

        guard result == GIT_OK.rawValue else {
            return callback(.failure(NSError(gitError: result, pointOfFailure: "git_remote_lookup")))
        }

        return callback(.success(pointer!))
    }

    /// Load a remote from the repository.
    ///
    /// name - The name of the remote.
    ///
    /// Returns the remote if it exists, or an error.
    public func remote(named name: String) -> Result<Remote, NSError> {
        remoteLookup(named: name) { $0.map(Remote.init) }
    }

    /// Download new data and update tips
    /// - Parameters:
    ///   - remote: The remote object
    ///   - proxy: The proxy object
    /// - Returns: Result void or failure
    public func fetch(_ remote: Remote, proxy: ProxyConfiguration?) -> Result<Void, NSError> {
        remoteLookup(named: remote.name) { remote in
            remote.flatMap { pointer in
                var opts = fetchOptions(credentials: .sshAgent, proxy: proxy)
                let resultInit = git_fetch_options_init(&opts, UInt32(GIT_FETCH_OPTIONS_VERSION))
                assert(resultInit == GIT_OK.rawValue)

                let result = git_remote_fetch(pointer, nil, &opts, nil)
                guard result == GIT_OK.rawValue else {
                    let err = NSError(gitError: result, pointOfFailure: "git_remote_fetch")
                    return .failure(err)
                }

                return .success(())
            }
        }
    }

    /// Fetch git repository
    /// - Parameters:
    ///   - remote: The remote repository information
    ///   - credentials: The credential information
    ///   - proxy: The proxy infirmation
    /// - Returns: Return a `Result<Void, NSError>`
    public func fetch(
        _ remote: Remote,
        credentials: Credentials = .default,
        proxy: ProxyConfiguration?
    ) -> Result<Void, NSError> {
        remoteLookup(named: remote.name) { remote in
            remote.flatMap { pointer in
                var opts: git_fetch_options
                if credentials != Credentials.default {
                    opts = fetchOptions(credentials: credentials, proxy: proxy)
                } else {
                    opts = git_fetch_options()
                    let resultInit = git_fetch_options_init(&opts, UInt32(GIT_FETCH_OPTIONS_VERSION))
                    assert(resultInit == GIT_OK.rawValue)
                }

                let result = git_remote_fetch(pointer, nil, &opts, nil)
                guard result == GIT_OK.rawValue else {
                    let err = NSError(gitError: result, pointOfFailure: "git_remote_fetch")
                    return .failure(err)
                }

                return .success(())
            }
        }
    }

    // MARK: - Pushing / Pulling

    // swiftlint:disable function_body_length

    /// Push branch to the specified remote.
    /// This method not use proxy needed to push like on push2
    /// If branch is a local branch, will try to push to the corresponding remote branch with the same name.
    /// - Parameters:
    ///   - remote: The remote git repository
    ///   - branch: The git branch
    ///   - credentials: The git credential
    /// - Returns: Return a `Result<Void, NSError>`
    public func push(
        remote: Remote, branch: Branch,
        credentials: Credentials? = nil
    ) -> Result<Void, NSError> {
        remoteLookup(named: remote.name) { result in
            result.flatMap { remote in
                let connectResult: Int32
                if let credentials {
                    var callbacks = git_remote_callbacks()
                    let initCallbacksResult = git_remote_init_callbacks(
                        &callbacks,
                        UInt32(GIT_REMOTE_CALLBACKS_VERSION)
                    )
                    guard initCallbacksResult == GIT_OK.rawValue else {
                        print(errorMessage(initCallbacksResult)!)
                        return Result
                            .failure(NSError(
                                gitError: initCallbacksResult,
                                pointOfFailure: "git_remote_init_callbacks"
                            ))
                    }

                    callbacks.payload = credentials.toPointer()
                    callbacks.credentials = credentialsCallback

                    connectResult = git_remote_connect(remote, GIT_DIRECTION_PUSH, &callbacks, nil, nil)
                } else {
                    connectResult = git_remote_connect(remote, GIT_DIRECTION_PUSH, nil, nil, nil)
                }
                guard connectResult == GIT_OK.rawValue else {
                    return Result
                        .failure(NSError(gitError: connectResult, pointOfFailure: "git_remote_connect"))
                }

                var options: git_push_options
                if let credentials {
                    options = pushOptions(credentials: credentials)
                } else {
                    options = git_push_options()
                    git_push_options_init(&options, UInt32(GIT_PUSH_OPTIONS_VERSION))
                }
                // lookup refspec
                var refspecArray = git_strarray()
                let getRefspecsResult = git_remote_get_push_refspecs(&refspecArray, remote)
                guard getRefspecsResult == GIT_OK.rawValue else {
                    return Result
                        .failure(NSError(
                            gitError: getRefspecsResult,
                            pointOfFailure: "git_remote_get_push_refspecs"
                        ))
                }

                defer { git_strarray_dispose(&refspecArray) }
                let branchRefspec = "\(branch.longName):\(branch.longName)"
                let refspec = refspecArray.filter { $0 == branchRefspec }.first ?? branchRefspec

                let ptrRefspec = strdup(refspec)
                defer { free(ptrRefspec) }
                var selectedRefspecs = [ptrRefspec]
                var selectedRefspecArray = selectedRefspecs.withUnsafeMutableBufferPointer { buffer in
                    git_strarray(strings: buffer.baseAddress, count: 1)
                }
                // do the push
                let uploadResult = git_remote_upload(remote, &selectedRefspecArray, &options)
                guard uploadResult == GIT_OK.rawValue else {
                    return Result
                        .failure(NSError(gitError: uploadResult, pointOfFailure: "git_remote_upload"))
                }

                return .success(())
            }
        }
    }

    // swiftlint:enable function_body_length

    // swiftlint:disable function_body_length

    /// Push change to the remote server version two
    /// - Parameters:
    ///   - remote: The git remote
    ///   - branch: The git branch
    ///   - credentials: The git credentials
    ///   - proxy: The git proxy
    /// - Returns: Return a `Result<Void, NSError>`
    public func push2(
        remote: Remote,
        branch: Branch,
        credentials: Credentials? = nil,
        proxy: ProxyConfiguration? = nil
    ) -> Result<Void, NSError> {
        remoteLookup(named: remote.name) { result in
            result.flatMap { remote in
                let connectResult: Int32
                let proxyOpts = UnsafeMutablePointer<git_proxy_options>.allocate(capacity: 1)
                defer { proxyOpts.deallocate() }
                proxyOpts.pointee = proxyOptions(proxy: proxy)
                if let credentials {
                    var callbacks = git_remote_callbacks()
                    let initCallbacksResult = git_remote_init_callbacks(
                        &callbacks,
                        UInt32(GIT_REMOTE_CALLBACKS_VERSION)
                    )
                    guard initCallbacksResult == GIT_OK.rawValue else {
                        print(errorMessage(initCallbacksResult)!)
                        return Result
                            .failure(NSError(
                                gitError: initCallbacksResult,
                                pointOfFailure: "git_remote_init_callbacks"
                            ))
                    }

                    callbacks.payload = credentials.toPointer()
                    callbacks.credentials = credentialsCallback

                    connectResult = git_remote_connect(
                        remote,
                        GIT_DIRECTION_PUSH,
                        &callbacks,
                        proxyOpts,
                        nil
                    )
                } else {
                    connectResult = git_remote_connect(remote, GIT_DIRECTION_PUSH, nil, proxyOpts, nil)
                }
                guard connectResult == GIT_OK.rawValue else {
                    return Result
                        .failure(NSError(gitError: connectResult, pointOfFailure: "git_remote_connect"))
                }

                var options: git_push_options
                if let credentials {
                    options = pushOptions(credentials: credentials, proxy: proxy)
                } else {
                    options = git_push_options()
                    git_push_options_init(&options, UInt32(GIT_PUSH_OPTIONS_VERSION))
                }
                // lookup refspec
                let ptrRefspec = strdup(branch.longName)
                defer { free(ptrRefspec) }
                var selectedRefspecs = [ptrRefspec]
                var selectedRefspecArray = selectedRefspecs.withUnsafeMutableBufferPointer { buffer in
                    git_strarray(strings: buffer.baseAddress, count: 1)
                }
                // do the push
                let uploadResult = git_remote_push(remote, &selectedRefspecArray, &options)
                guard uploadResult == GIT_OK.rawValue else {
                    return Result
                        .failure(NSError(gitError: uploadResult, pointOfFailure: "git_remote_upload"))
                }

                return .success(())
            }
        }
    }

    // swiftlint:enable function_body_length

    /// The Git conflict decision
    public enum ConflictResolutionDecision {
        /// Keep our version of the conflicted file.
        case ours
        /// Keep their version of the conflicted file.
        case theirs
        /// Use the provided data as the resolved content.
        case merge(Data)
    }

    /// Takes in "our" side and "their" side of the file respectively, and returns a decision
    public typealias ConflictResolver = (Data, Data) -> ConflictResolutionDecision

    // swiftlint:disable cyclomatic_complexity function_body_length function_parameter_count

    /// Pulls from the remote and updates our local branch.
    /// inspired by https://github.com/SwiftGit2/SwiftGit2/pull/125/files
    /// - Parameters:
    ///   - remote: The git remote
    ///   - branch: The git branch
    ///   - author: The git author
    ///   - email: The git email
    ///   - credentials: The git credentials
    ///   - proxy: The proxy infirmation
    ///   - conflictResolver: The conflict resolver
    /// - Returns: Result<Void, NSError>
    public func pull(
        remote: Remote,
        branch: Branch,
        author: String,
        email: String,
        credentials: Credentials = .default,
        proxy: ProxyConfiguration?,
        conflictResolver _: ConflictResolver
    ) -> Result<Void, NSError> {
        // first initiate a fetch
        fetch(remote, credentials: credentials, proxy: proxy).flatMap { _ in
            let localBranchResult = self.localBranch(named: branch.name)
            guard case let .success(localBranch) = localBranchResult else {
                return localBranchResult.map { _ in () }
            }

            // determine if we need to perform a merge
            // if local commit is the same as remote commit, no need
            return branch.getTrackingBranch(repo: self).flatMap { trackingBranch in
                // determine if the local branch can be fast-forwarded
                guard localBranch.oid != trackingBranch.oid else {
                    return .success(())
                }

                // determine if a clean merge can be performed
                var annotatedCommit: OpaquePointer?
                var oid = trackingBranch.oid.oid
                let lookupResult = git_annotated_commit_lookup(&annotatedCommit, self.pointer, &oid)
                guard lookupResult == GIT_OK.rawValue else {
                    return Result
                        .failure(NSError(
                            gitError: lookupResult,
                            pointOfFailure: "git_annotated_commit_lookup"
                        ))
                }

                defer { git_annotated_commit_free(annotatedCommit) }
                var analysis = GIT_MERGE_ANALYSIS_NONE
                var preference = GIT_MERGE_PREFERENCE_NONE
                let analysisResult = git_merge_analysis(
                    &analysis,
                    &preference,
                    self.pointer,
                    &annotatedCommit,
                    1
                )
                guard analysisResult == GIT_OK.rawValue else {
                    return Result
                        .failure(NSError(gitError: analysisResult, pointOfFailure: "git_merge_analysis"))
                }

                if analysis.rawValue & GIT_MERGE_ANALYSIS_UP_TO_DATE.rawValue != 0 {
                    // nothing needs to be done
                    return .success(())
                } else if analysis.rawValue & GIT_MERGE_ANALYSIS_UNBORN.rawValue != 0
                    || analysis.rawValue & GIT_MERGE_ANALYSIS_FASTFORWARD.rawValue != 0 {
                    // fast-forward local branch
                    let message = "merge \(remote.name)/\(trackingBranch.name): Fast-forward"
                    return localBranch.referenceByUpdatingTarget(
                        repo: self,
                        newTarget: trackingBranch.oid,
                        message: message
                    ).flatMap { newRef in
                        self.checkout(newRef.oid, strategy: CheckoutStrategy.Force)
                    }
                } else if analysis.rawValue & GIT_MERGE_ANALYSIS_NORMAL.rawValue != 0 {
                    // normal merge
                    return unsafeTreeForCommitId(localBranch.commit.oid).flatMap { localTree in
                        defer { git_tree_free(localTree) }
                        return unsafeTreeForCommitId(trackingBranch.commit.oid).flatMap { remoteTree in
                            defer { git_tree_free(remoteTree) }
                            var baseTreePointer: OpaquePointer?
                            defer { git_tree_free(baseTreePointer) }
                            // check conflicts
                            var index: OpaquePointer?
                            var baseOid = git_oid()
                            var localOid = localBranch.commit.oid.oid
                            var remoteOid = trackingBranch.commit.oid.oid
                            let findMergeBaseResult = git_merge_base(
                                &baseOid,
                                self.pointer,
                                &localOid,
                                &remoteOid
                            )
                            if findMergeBaseResult == GIT_OK.rawValue {
                                let result = commit(OID(baseOid))
                                    .flatMap { baseCommit -> Result<Void, NSError> in
                                        unsafeTreeForCommitId(baseCommit.oid)
                                            .flatMap { baseTree -> Result<Void, NSError> in
                                                baseTreePointer = baseTree
                                                return .success(())
                                            }
                                    }
                                if case .failure = result {
                                    return result
                                }
                            }
                            let mergeTreeResult = git_merge_trees(
                                &index,
                                self.pointer,
                                baseTreePointer,
                                localTree,
                                remoteTree,
                                nil
                            )
                            guard mergeTreeResult == GIT_OK.rawValue else {
                                return Result
                                    .failure(NSError(
                                        gitError: mergeTreeResult,
                                        pointOfFailure: "git_merge_trees"
                                    ))
                            }

                            // if a clean merge cannot be performed,
                            // call the user-supplied conflict resolver
                            if git_index_has_conflicts(index!) > 0 {
                                fatalError()
                            }
                            var treeOid = git_oid()
                            let writeTreeResult = git_index_write_tree_to(&treeOid, index!, self.pointer)
                            guard writeTreeResult == GIT_OK.rawValue else {
                                return Result
                                    .failure(NSError(
                                        gitError: writeTreeResult,
                                        pointOfFailure: "git_index_write_tree"
                                    ))
                            }

                            // create merge commit
                            var parents: [Commit] = []
                            for commitMerge in [
                                commit(localBranch.commit.oid),
                                commit(trackingBranch.commit.oid)
                            ] {
                                if case .failure = commitMerge {
                                    return commitMerge.map { _ in () }
                                } else if case let .success(commit) = commitMerge {
                                    parents.append(commit)
                                }
                            }
                            let message = "Merge branch '\(localBranch.shortName ?? localBranch.name)'"
                            return commit(
                                index: index,
                                tree: treeOid,
                                parents: parents,
                                message: message,
                                author: author,
                                email: email
                            ).flatMap { commit in
                                checkout(commit.oid, strategy: CheckoutStrategy.Force)
                            }
                        }
                    }
                } else {
                    return Result
                        .failure(NSError(gitError: analysisResult, pointOfFailure: "decoding merge result"))
                }
            }
        }
    }

    // swiftlint:enable cyclomatic_complexity function_body_length function_parameter_count

    /// Pulls from the remote and updates our local branch.
    /// https://github.com/SwiftGit2/SwiftGit2/pull/129/files
    /// - Parameters:
    ///   - remote: The git remote
    ///   - branch: The git branch
    ///   - signatureMaker: The git signature
    ///   - credentials: The git credentials
    ///   - proxy: the proxy information
    ///   - _: The git conflict resolver
    ///   - progress: The git progress
    /// - Returns: return a `Result<Void, NSError>`
    public func pull2( // swiftlint:disable:this function_body_length cyclomatic_complexity
        remote: Remote,
        branch: Branch,
        signatureMaker: () -> Signature,
        credentials: Credentials = .default,
        proxy: ProxyConfiguration?,
        conflictResolver _: ConflictResolver,
        progress: CheckoutProgressBlock? = nil
    ) -> Result<Void, NSError> {
        // first initiate a fetch
        fetch(remote, credentials: credentials, proxy: proxy).flatMap { _ in
            let localBranchResult = self.localBranch(named: branch.name)
            guard case let .success(localBranch) = localBranchResult else {
                return localBranchResult.map { _ in () }
            }

            // determine if we need to perform a merge
            // if local commit is the same as remote commit, no need
            return branch.getTrackingBranch(repo: self).flatMap { trackingBranch in
                // determine if the local branch can be fast-forwarded
                guard localBranch.oid != trackingBranch.oid else {
                    return .success(())
                }

                // determine if a clean merge can be performed
                var annotatedCommit: OpaquePointer?
                var oid = trackingBranch.oid.oid
                let lookupResult = git_annotated_commit_lookup(&annotatedCommit, self.pointer, &oid)
                guard lookupResult == GIT_OK.rawValue else {
                    return Result
                        .failure(NSError(
                            gitError: lookupResult,
                            pointOfFailure: "git_annotated_commit_lookup"
                        ))
                }

                defer { git_annotated_commit_free(annotatedCommit) }
                var analysis = GIT_MERGE_ANALYSIS_NONE
                var preference = GIT_MERGE_PREFERENCE_NONE
                let analysisResult = git_merge_analysis(
                    &analysis,
                    &preference,
                    self.pointer,
                    &annotatedCommit,
                    1
                )
                guard analysisResult == GIT_OK.rawValue else {
                    return Result
                        .failure(NSError(gitError: analysisResult, pointOfFailure: "git_merge_analysis"))
                }

                if analysis.rawValue & GIT_MERGE_ANALYSIS_UP_TO_DATE.rawValue != 0 {
                    // nothing needs to be done
                    return .success(())
                } else if analysis.rawValue & GIT_MERGE_ANALYSIS_UNBORN.rawValue != 0
                    || analysis.rawValue & GIT_MERGE_ANALYSIS_FASTFORWARD.rawValue != 0 {
                    // fast-forward local branch
                    let message = "merge \(remote.name)/\(trackingBranch.name): Fast-forward"
                    return localBranch.referenceByUpdatingTarget(
                        repo: self,
                        newTarget: trackingBranch.oid,
                        message: message
                    ).flatMap { newRef in
                        self.checkout(newRef.oid, strategy: CheckoutStrategy.Force, progress: progress)
                    }
                } else if analysis.rawValue & GIT_MERGE_ANALYSIS_NORMAL.rawValue != 0 {
                    // normal merge
                    return unsafeTreeForCommitId(localBranch.commit.oid).flatMap { localTree in
                        defer { git_tree_free(localTree) }
                        return unsafeTreeForCommitId(trackingBranch.commit.oid).flatMap { remoteTree in
                            defer { git_tree_free(remoteTree) }
                            // check conflicts
                            var index: OpaquePointer?
                            var baseOID = git_oid()
                            var localOID = localBranch.commit.oid.oid
                            var remoteOID = trackingBranch.commit.oid.oid
                            let findMergeBaseResult = git_merge_base(
                                &baseOID,
                                self.pointer,
                                &localOID,
                                &remoteOID
                            )
                            var baseTree: OpaquePointer?
                            if findMergeBaseResult == GIT_OK.rawValue {
                                let result = commit(OID(baseOID))
                                    .flatMap { baseCommit -> Result<Void, NSError> in
                                        unsafeTreeForCommitId(baseCommit.oid)
                                            .flatMap { baseTreeUnsafe -> Result<Void, NSError> in
                                                baseTree = baseTreeUnsafe
                                                return .success(())
                                            }
                                    }
                                if case .failure = result {
                                    return result
                                }
                            }
                            let mergeTreeResult = git_merge_trees(
                                &index,
                                self.pointer,
                                baseTree,
                                localTree,
                                remoteTree,
                                nil
                            )
                            guard mergeTreeResult == GIT_OK.rawValue else {
                                return Result
                                    .failure(NSError(
                                        gitError: mergeTreeResult,
                                        pointOfFailure: "git_merge_trees"
                                    ))
                            }

                            // if a clean merge cannot be performed,
                            // call the user-supplied conflict resolver
                            if git_index_has_conflicts(index!) > 0 {
                                fatalError()
                            }
                            var treeOID = git_oid()
                            let writeTreeResult = git_index_write_tree_to(&treeOID, index!, self.pointer)
                            guard writeTreeResult == GIT_OK.rawValue else {
                                return Result
                                    .failure(NSError(
                                        gitError: writeTreeResult,
                                        pointOfFailure: "git_index_write_tree"
                                    ))
                            }

                            // create merge commit
                            var parents: [Commit] = []
                            for parent in [
                                commit(localBranch.commit.oid),
                                commit(trackingBranch.commit.oid)
                            ] {
                                if case .failure = parent {
                                    return parent.map { _ in () }
                                } else if case let .success(commit) = parent {
                                    parents.append(commit)
                                }
                            }
                            let message = "Merge branch '\(localBranch.shortName ?? localBranch.name)'"
                            git_tree_free(baseTree)
                            return commit(
                                tree: OID(treeOID),
                                parents: parents,
                                message: message,
                                signature: signatureMaker()
                            ).flatMap { commit in
                                checkout(commit.oid, strategy: CheckoutStrategy.Force, progress: progress)
                            }
                        }
                    }
                } else {
                    return Result
                        .failure(NSError(gitError: analysisResult, pointOfFailure: "decoding merge result"))
                }
            }
        }
    }

    // MARK: - Reference Lookups

    /// Load all the references with the given prefix (e.g. "refs/heads/")
    /// - Parameter prefix: The prefix of the branch
    /// - Returns: Return a `Result<[ReferenceType], NSError>`
    public func references(withPrefix prefix: String) -> Result<[ReferenceType], NSError> {
        let pointer = UnsafeMutablePointer<git_strarray>.allocate(capacity: 1)
        let result = git_reference_list(pointer, self.pointer)

        guard result == GIT_OK.rawValue else {
            pointer.deallocate()
            return Result.failure(NSError(gitError: result, pointOfFailure: "git_reference_list"))
        }

        let strarray = pointer.pointee
        let references = strarray
            .filter {
                $0.hasPrefix(prefix)
            }
            .map {
                self.reference(named: $0)
            }
        git_strarray_dispose(pointer)
        pointer.deallocate()

        return references.aggregateResult()
    }

    /// Load the reference with the given long name (e.g. "refs/heads/master")
    ///
    /// If the reference is a branch, a `Branch` will be returned. If the
    /// reference is a tag, a `TagReference` will be returned. Otherwise, a
    /// `Reference` will be returned.
    /// - Parameter name: The name of the reference
    /// - Returns: Return a `Result<ReferenceType, NSError>`
    public func reference(named name: String) -> Result<ReferenceType, NSError> {
        var pointer: OpaquePointer?
        let result = git_reference_lookup(&pointer, self.pointer, name)

        guard result == GIT_OK.rawValue else {
            return Result.failure(NSError(gitError: result, pointOfFailure: "git_reference_lookup"))
        }

        let value = referenceWithLibGit2Reference(pointer!)
        git_reference_free(pointer)
        return .success(value)
    }

    /// Load and return a list of all local branches.
    public func localBranches() -> Result<[Branch], NSError> {
        references(withPrefix: "refs/heads/")
            .map { (refs: [ReferenceType]) in
                refs.map { $0 as! Branch } // swiftlint:disable:this force_cast
            }
    }

    /// Load and return a list of all remote branches.
    public func remoteBranches() -> Result<[Branch], NSError> {
        references(withPrefix: "refs/remotes/")
            .map { (refs: [ReferenceType]) in
                refs.map { $0 as! Branch } // swiftlint:disable:this force_cast
            }
    }

    /// Load the local branch with the given name (e.g., "master").
    /// - Parameter name: The branch name
    /// - Returns: Return a `Result<Branch, NSError>`
    public func localBranch(named name: String) -> Result<Branch, NSError> {
        reference(named: "refs/heads/" + name)
            .map { $0 as! Branch } // swiftlint:disable:this force_cast
    }

    /// Load the remote branch with the given name (e.g., "origin/master").
    /// - Parameter name: The remote branch name
    /// - Returns: Return a `Result<Branch, NSError>`
    public func remoteBranch(named name: String) -> Result<Branch, NSError> {
        reference(named: "refs/remotes/" + name)
            .map { $0 as! Branch } // swiftlint:disable:this force_cast
    }

    /// Load and return a list of all the `TagReference`s.
    /// - Returns: Return a `Result<[TagReference], NSError>`
    public func allTags() -> Result<[TagReference], NSError> {
        references(withPrefix: "refs/tags/")
            .map { (refs: [ReferenceType]) in
                refs.map { $0 as! TagReference } // swiftlint:disable:this force_cast
            }
    }

    /// Load the tag with the given name (e.g., "tag-2").
    /// - Parameter name: The tag name
    /// - Returns: Return a `Result<TagReference, NSError>`
    public func tag(named name: String) -> Result<TagReference, NSError> {
        reference(named: "refs/tags/" + name)
            .map { $0 as! TagReference } // swiftlint:disable:this force_cast
    }

    // MARK: - Working Directory

    /// Load the reference pointed at by HEAD.
    ///
    /// When on a branch, this will return the current `Branch`.
    /// - Returns: Return a `Result<ReferenceType, NSError>`
    public func HEAD() -> Result<ReferenceType, NSError> {
        var pointer: OpaquePointer?
        let result = git_repository_head(&pointer, self.pointer)
        guard result == GIT_OK.rawValue else {
            return Result.failure(NSError(gitError: result, pointOfFailure: "git_repository_head"))
        }

        let value = referenceWithLibGit2Reference(pointer!)
        git_reference_free(pointer)
        return Result.success(value)
    }

    /// Set HEAD to the given oid (detached).
    ///
    /// :param: oid The OID to set as HEAD.
    /// :returns: Returns a result with void or the error that occurred.
    /// - Parameter oid: The id of the commit
    /// - Returns: Return a `Result<Void, NSError>`
    public func setHEAD(_ oid: OID) -> Result<Void, NSError> {
        var oid = oid.oid
        let result = git_repository_set_head_detached(pointer, &oid)
        guard result == GIT_OK.rawValue else {
            return Result
                .failure(NSError(gitError: result, pointOfFailure: "git_repository_set_head_detached"))
        }

        return Result.success(())
    }

    /// Set HEAD to the given reference.
    ///
    /// :param: reference The reference to set as HEAD.
    /// :returns: Returns a result with void or the error that occurred.
    public func setHEAD(_ reference: ReferenceType) -> Result<Void, NSError> {
        let result = git_repository_set_head(pointer, reference.longName)
        guard result == GIT_OK.rawValue else {
            return Result.failure(NSError(gitError: result, pointOfFailure: "git_repository_set_head"))
        }

        return Result.success(())
    }

    // MARK: - Checkout

    /// Check out HEAD.
    ///
    /// :param: strategy The checkout strategy to use.
    /// :param: progress A block that's called with the progress of the checkout.
    /// :returns: Returns a result with void or the error that occurred.
    public func checkout(
        strategy: CheckoutStrategy,
        progress: CheckoutProgressBlock? = nil
    ) -> Result<Void, NSError> {
        var options = checkoutOptions(strategy: strategy, progress: progress)

        let result = git_checkout_head(pointer, &options)
        guard result == GIT_OK.rawValue else {
            return Result.failure(NSError(gitError: result, pointOfFailure: "git_checkout_head"))
        }

        return Result.success(())
    }

    /// Check out the given OID.
    ///
    /// :param: oid The OID of the commit to check out.
    /// :param: strategy The checkout strategy to use.
    /// :param: progress A block that's called with the progress of the checkout.
    /// :returns: Returns a result with void or the error that occurred.
    public func checkout(
        _ oid: OID,
        strategy: CheckoutStrategy,
        progress: CheckoutProgressBlock? = nil
    ) -> Result<Void, NSError> {
        setHEAD(oid).flatMap { self.checkout(strategy: strategy, progress: progress) }
    }

    /// Check out the given reference.
    ///
    /// :param: reference The reference to check out.
    /// :param: strategy The checkout strategy to use.
    /// :param: progress A block that's called with the progress of the checkout.
    /// :returns: Returns a result with void or the error that occurred.
    public func checkout(
        _ reference: ReferenceType,
        strategy: CheckoutStrategy,
        progress: CheckoutProgressBlock? = nil
    ) -> Result<Void, NSError> {
        setHEAD(reference).flatMap { self.checkout(strategy: strategy, progress: progress) }
    }

    /// checkout to the given branch
    /// - Parameter branch: The branch
    /// - Returns: Returns a result with void or the error that occurred.
    public func checkout(_ branch: Branch) -> Result<Void, NSError> {
        let branchName = branch.longName
        let result = branchName.withCString {
            git_repository_set_head(pointer, $0)
        }
        guard result == GIT_OK.rawValue else {
            return Result.failure(NSError(gitError: result, pointOfFailure: "git_repository_set_head"))
        }

        return Result.success(())
    }

    // MARK: - Commit

    /// Performs a commit of the staged files with the specified message and author
    public func commit( // swiftlint:disable:this function_parameter_count
        index _: OpaquePointer!,
        tree treeOid: git_oid,
        parents: [Commit],
        message: String,
        author: String,
        email: String
    ) -> Result<Commit, NSError> {
        // create commit signature
        var signature: UnsafeMutablePointer<git_signature>?
        let time = git_time_t(NSDate().timeIntervalSince1970) // Unix epoch time
        let offset: Int32 = 0
        let signatureResult = git_signature_new(&signature, author, email, time, offset)
        guard signatureResult == GIT_OK.rawValue else {
            let err = NSError(gitError: signatureResult, pointOfFailure: "git_signature_new")
            return .failure(err)
        }

        var tree: OpaquePointer?
        var treeOidVar = treeOid
        let lookupResult = git_tree_lookup(&tree, pointer, &treeOidVar)
        guard lookupResult == GIT_OK.rawValue else {
            let err = NSError(gitError: lookupResult, pointOfFailure: "git_tree_lookup")
            return .failure(err)
        }

        var msgBuf = git_buf()
        git_message_prettify(&msgBuf, message, 0, /* ascii for # */ 35)

        // use HEAD as parent
        var parentC: [OpaquePointer?] = []
        for parentCommit in parents {
            var parent: OpaquePointer?
            var oid = parentCommit.oid.oid
            git_commit_lookup(&parent, pointer, &oid)
            parentC.append(parent!)
        }

        let parentsContiguous = ContiguousArray(parentC)
        return parentsContiguous.withUnsafeBufferPointer { pointer in
            var commitOid = git_oid()
            let parentsPtr = UnsafeMutablePointer(mutating: pointer.baseAddress)
            let result = git_commit_create(
                &commitOid,
                self.pointer,
                "HEAD",
                signature,
                signature,
                nil,
                msgBuf.ptr,
                tree,
                parents.count,
                parentsPtr
            )

            git_buf_dispose(&msgBuf)
            git_signature_free(signature)
            git_tree_free(tree)

            guard result == GIT_OK.rawValue else {
                let err = NSError(gitError: result, pointOfFailure: "git_commit_create")
                return .failure(err)
            }

            return commit(OID(commitOid))
        }
    }

    /// The current tip as the single parent of a new commit, or no parent when HEAD is unborn.
    private func headParents() -> Result<[Commit], NSError> {
        var parentID = git_oid()
        let result = git_reference_name_to_id(&parentID, pointer, "HEAD")
        if result == GIT_ENOTFOUND.rawValue {
            return .success([])
        }
        guard result == GIT_OK.rawValue else {
            return .failure(NSError(gitError: result, pointOfFailure: "git_reference_name_to_id"))
        }

        return commit(OID(parentID)).map { [$0] }
    }

    /// Performs a commit of the staged files with the specified message and author
    public func commit(message: String, author: String, email: String) -> Result<Commit, NSError> {
        unsafeIndex().flatMap { index in
            defer { git_index_free(index) }
            var treeOid = git_oid()
            let treeResult = git_index_write_tree(&treeOid, index)
            guard treeResult == GIT_OK.rawValue else {
                let err = NSError(gitError: treeResult, pointOfFailure: "git_index_write_tree")
                return .failure(err)
            }

            return headParents().flatMap { parents in
                commit(
                    index: index,
                    tree: treeOid,
                    parents: parents,
                    message: message,
                    author: author,
                    email: email
                )
            }
        }
    }

    /// Load all commits in the specified branch in topological & time order descending
    ///
    /// :param: branch The branch to get all commits from
    /// :returns: Returns a result with array of branches or the error that occurred
    public func commits(in branch: Branch) -> CommitIterator {
        CommitIterator(repo: self, root: branch.oid.oid)
    }

    /// Returns the number of commits reachable from the given branch.
    public func numberOfCommits(in branch: Branch) -> Int {
        var count = 0
        let commits = commits(in: branch)
        while commits.next() != nil {
            count += 1
        }
        return count
    }

    /// Get the index for the repo. The caller is responsible for freeing the index.
    func unsafeIndex() -> Result<OpaquePointer, NSError> {
        var index: OpaquePointer?
        let result = git_repository_index(&index, pointer)
        guard result == GIT_OK.rawValue, index != nil else {
            let err = NSError(gitError: result, pointOfFailure: "git_repository_index")
            return .failure(err)
        }

        return .success(index!)
    }

    /// Stage the file(s) under the specified path.
    public func add(path: String) -> Result<Void, NSError> {
        let dir = path
        var dirPointer = UnsafeMutablePointer<Int8>(mutating: (dir as NSString).utf8String)
        var paths = withUnsafeMutablePointer(to: &dirPointer) {
            git_strarray(strings: $0, count: 1)
        }
        return unsafeIndex().flatMap { index in
            defer { git_index_free(index) }

            // add this to print or log added files
            // let pointer = UnsafeMutablePointer<git_index_matched_path_cb>.allocate(capacity: 1)
            // var options = pointer.move()
            // pointer.deallocate()
            // options = printMatchedCBCallback

            // var repository = self

            let addResult = git_index_add_all(index, &paths, 0, nil, nil)
            guard addResult == GIT_OK.rawValue else {
                return .failure(NSError(gitError: addResult, pointOfFailure: "git_index_add_all"))
            }

            // write index to disk
            let writeResult = git_index_write(index)
            guard writeResult == GIT_OK.rawValue else {
                return .failure(NSError(gitError: writeResult, pointOfFailure: "git_index_write"))
            }

            return .success(())
        }
    }

    /// Perform a commit with arbitrary numbers of parent commits.
    public func commit( // swiftlint:disable:this function_body_length
        tree treeOID: OID,
        parents: [Commit],
        message: String,
        signature: Signature
    ) -> Result<Commit, NSError> {
        // create commit signature
        signature.makeUnsafeSignature().flatMap { signature in
            defer { git_signature_free(signature) }
            var tree: OpaquePointer?
            var treeOIDCopy = treeOID.oid
            let lookupResult = git_tree_lookup(&tree, self.pointer, &treeOIDCopy)
            guard lookupResult == GIT_OK.rawValue else {
                let err = NSError(gitError: lookupResult, pointOfFailure: "git_tree_lookup")
                return .failure(err)
            }

            defer { git_tree_free(tree) }

            var msgBuf = git_buf()
            git_message_prettify(&msgBuf, message, 0, /* ascii for # */ 35)
            defer { git_buf_dispose(&msgBuf) }

            // libgit2 expects a C-like array of parent git_commit pointer
            var parentGitCommits: [OpaquePointer?] = []
            defer {
                for commit in parentGitCommits {
                    git_commit_free(commit)
                }
            }
            for parentCommit in parents {
                var parent: OpaquePointer?
                var oid = parentCommit.oid.oid
                let lookupResult = git_commit_lookup(&parent, self.pointer, &oid)
                guard lookupResult == GIT_OK.rawValue else {
                    let err = NSError(gitError: lookupResult, pointOfFailure: "git_commit_lookup")
                    return .failure(err)
                }

                parentGitCommits.append(parent!)
            }

            let parentsContiguous = ContiguousArray(parentGitCommits)
            return parentsContiguous.withUnsafeBufferPointer { unsafeBuffer in
                var commitOID = git_oid()
                let parentsPtr = UnsafeMutablePointer(mutating: unsafeBuffer.baseAddress)
                let result = git_commit_create(
                    &commitOID,
                    self.pointer,
                    "HEAD",
                    signature,
                    signature,
                    "UTF-8",
                    msgBuf.ptr,
                    tree,
                    parents.count,
                    parentsPtr
                )
                guard result == GIT_OK.rawValue else {
                    return .failure(NSError(gitError: result, pointOfFailure: "git_commit_create"))
                }

                return commit(OID(commitOID))
            }
        }
    }

    /// Perform a commit of the staged files with the specified message and signature,
    /// assuming we are not doing a merge and using the current tip as the parent.
    public func commit(message: String, signature: Signature) -> Result<Commit, NSError> {
        unsafeIndex().flatMap { index in
            defer { git_index_free(index) }
            var treeOID = git_oid()
            let treeResult = git_index_write_tree(&treeOID, index)
            guard treeResult == GIT_OK.rawValue else {
                let err = NSError(gitError: treeResult, pointOfFailure: "git_index_write_tree")
                return .failure(err)
            }

            return headParents().flatMap { parents in
                commit(tree: OID(treeOID), parents: parents, message: message, signature: signature)
            }
        }
    }

    // MARK: - Diffs

    /// Perform a diff.
    public func diff(for commit: Commit) -> Result<Diff, NSError> {
        guard !commit.parents.isEmpty else {
            // Initial commit in a repository
            return diff(from: nil, to: commit.oid)
        }

        var mergeDiff: OpaquePointer?
        defer { git_object_free(mergeDiff) }
        for parent in commit.parents {
            let error = diff(from: parent.oid, to: commit.oid) {
                switch $0 {
                case let .failure(error):
                    return error

                case let .success(newDiff):
                    if mergeDiff == nil {
                        mergeDiff = newDiff
                    } else {
                        let mergeResult = git_diff_merge(mergeDiff, newDiff)
                        guard mergeResult == GIT_OK.rawValue else {
                            return NSError(gitError: mergeResult, pointOfFailure: "git_diff_merge")
                        }
                    }
                    return nil
                }
            }

            if error != nil {
                return Result<Diff, NSError>.failure(error!)
            }
        }

        return .success(Diff(mergeDiff!))
    }

    private func diff(
        from oldCommitOid: OID?,
        to newCommitOid: OID?,
        transform: (Result<OpaquePointer, NSError>) -> NSError?
    ) -> NSError? {
        assert(
            oldCommitOid != nil || newCommitOid != nil,
            "It is an error to pass nil for both the oldOid and newOid"
        )

        var oldTree: OpaquePointer?
        defer { git_object_free(oldTree) }
        if let oid = oldCommitOid {
            switch unsafeTreeForCommitId(oid) {
            case let .failure(error):
                return transform(.failure(error))
            case let .success(value):
                oldTree = value
            }
        }

        var newTree: OpaquePointer?
        defer { git_object_free(newTree) }
        if let oid = newCommitOid {
            switch unsafeTreeForCommitId(oid) {
            case let .failure(error):
                return transform(.failure(error))
            case let .success(value):
                newTree = value
            }
        }

        var diff: OpaquePointer?
        let diffResult = git_diff_tree_to_tree(
            &diff,
            pointer,
            oldTree,
            newTree,
            nil
        )

        guard diffResult == GIT_OK.rawValue else {
            return transform(.failure(NSError(
                gitError: diffResult,
                pointOfFailure: "git_diff_tree_to_tree"
            )))
        }

        return transform(Result<OpaquePointer, NSError>.success(diff!))
    }

    /// Perform a diff.
    private func diff( // swiftlint:disable:this function_body_length
        from oldCommitOid: OID?,
        to newCommitOid: OID?
    ) -> Result<Diff, NSError> {
        assert(
            oldCommitOid != nil || newCommitOid != nil,
            "It is an error to pass nil for both the oldOid and newOid"
        )

        var oldTree: Tree?
        if let oldCommitOid {
            switch safeTreeForCommitId(oldCommitOid) {
            case let .failure(error):
                return .failure(error)
            case let .success(value):
                oldTree = value
            }
        }

        var newTree: Tree?
        if let newCommitOid {
            switch safeTreeForCommitId(newCommitOid) {
            case let .failure(error):
                return .failure(error)
            case let .success(value):
                newTree = value
            }
        }

        if oldTree != nil, newTree != nil {
            return withGitObjects([oldTree!.oid, newTree!.oid], type: GIT_OBJECT_TREE) { objects in
                var diff: OpaquePointer?
                let diffResult = git_diff_tree_to_tree(
                    &diff,
                    self.pointer,
                    objects[0],
                    objects[1],
                    nil
                )
                return processTreeToTreeDiff(diffResult, diff: diff)
            }
        } else if let tree = oldTree {
            return withGitObject(tree.oid, type: GIT_OBJECT_TREE, transform: { tree in
                var diff: OpaquePointer?
                let diffResult = git_diff_tree_to_tree(
                    &diff,
                    self.pointer,
                    tree,
                    nil,
                    nil
                )
                return processTreeToTreeDiff(diffResult, diff: diff)
            })
        } else if let tree = newTree {
            return withGitObject(tree.oid, type: GIT_OBJECT_TREE, transform: { tree in
                var diff: OpaquePointer?
                let diffResult = git_diff_tree_to_tree(
                    &diff,
                    self.pointer,
                    nil,
                    tree,
                    nil
                )
                return processTreeToTreeDiff(diffResult, diff: diff)
            })
        }

        return .failure(NSError(gitError: -1, pointOfFailure: "diff(from: to:)"))
    }

    private func processTreeToTreeDiff(_ diffResult: Int32, diff: OpaquePointer?) -> Result<Diff, NSError> {
        guard diffResult == GIT_OK.rawValue else {
            return .failure(NSError(
                gitError: diffResult,
                pointOfFailure: "git_diff_tree_to_tree"
            ))
        }

        let diffObj = Diff(diff!)
        git_diff_free(diff)
        return .success(diffObj)
    }

    private func processDiffDeltas(_ diffResult: OpaquePointer) -> Result<[Diff.Delta], NSError> {
        var returnDict = [Diff.Delta]()

        let count = git_diff_num_deltas(diffResult)

        for i in 0 ..< count {
            let delta = git_diff_get_delta(diffResult, i)
            let gitDiffDelta = Diff.Delta((delta?.pointee)!)

            returnDict.append(gitDiffDelta)
        }

        return Result<[Diff.Delta], NSError>.success(returnDict)
    }

    private func safeTreeForCommitId(_ oid: OID) -> Result<Tree, NSError> {
        withGitObject(oid, type: GIT_OBJECT_COMMIT) { commit in
            let treeId = git_commit_tree_id(commit)
            return tree(OID(treeId!.pointee))
        }
    }

    /// Caller responsible to free returned tree with git_object_free
    private func unsafeTreeForCommitId(_ oid: OID) -> Result<OpaquePointer, NSError> {
        var commit: OpaquePointer?
        var oid = oid.oid
        let commitResult = git_object_lookup(&commit, pointer, &oid, GIT_OBJECT_COMMIT)
        guard commitResult == GIT_OK.rawValue else {
            return .failure(NSError(gitError: commitResult, pointOfFailure: "git_object_lookup"))
        }

        var tree: OpaquePointer?
        let treeId = git_commit_tree_id(commit)
        let treeResult = git_object_lookup(&tree, pointer, treeId, GIT_OBJECT_TREE)

        git_object_free(commit)

        guard treeResult == GIT_OK.rawValue else {
            return .failure(NSError(gitError: treeResult, pointOfFailure: "git_object_lookup"))
        }

        return Result<OpaquePointer, NSError>.success(tree!)
    }

    // MARK: - Status

    /// The status of the current repository
    /// - Parameter options: The status options
    /// - Returns: An array of `StatusEntry`
    public func status(options: StatusOptions = [.includeUntracked]) -> Result<[StatusEntry], NSError> {
        var returnArray = [StatusEntry]()

        // Do this because GIT_STATUS_OPTIONS_INIT is unavailable in swift
        let pointer = UnsafeMutablePointer<git_status_options>.allocate(capacity: 1)
        let optionsResult = git_status_options_init(pointer, UInt32(GIT_STATUS_OPTIONS_VERSION))
        guard optionsResult == GIT_OK.rawValue else {
            return .failure(NSError(gitError: optionsResult, pointOfFailure: "git_status_init_options"))
        }

        var listOptions = pointer.move()
        listOptions.flags = options.rawValue
        pointer.deallocate()

        var unsafeStatus: OpaquePointer?
        defer { git_status_list_free(unsafeStatus) }
        let statusResult = git_status_list_new(&unsafeStatus, self.pointer, &listOptions)
        guard statusResult == GIT_OK.rawValue, let unwrapStatusResult = unsafeStatus else {
            return .failure(NSError(gitError: statusResult, pointOfFailure: "git_status_list_new"))
        }

        let count = git_status_list_entrycount(unwrapStatusResult)

        for i in 0 ..< count {
            let sERTY = git_status_byindex(unwrapStatusResult, i)
            if sERTY?.pointee.status.rawValue == GIT_STATUS_CURRENT.rawValue {
                continue
            }

            let statusEntry = StatusEntry(from: sERTY!.pointee)
            returnArray.append(statusEntry)
        }

        return .success(returnArray)
    }

    // MARK: - Validity/Existence Check

    /// - returns: `.success(true)` iff there is a git repository at `url`,
    ///   `.success(false)` if there isn't,
    ///   and a `.failure` if there's been an error.
    public static func isValid(url: URL) -> Result<Bool, NSError> {
        var pointer: OpaquePointer?

        let result = url.withUnsafeFileSystemRepresentation {
            git_repository_open_ext(&pointer, $0, GIT_REPOSITORY_OPEN_NO_SEARCH.rawValue, nil)
        }

        switch result {
        case GIT_ENOTFOUND.rawValue:
            return .success(false)
        case GIT_OK.rawValue:
            return .success(true)
        default:
            return .failure(NSError(gitError: result, pointOfFailure: "git_repository_open_ext"))
        }
    }

    /// Returns the number of commits `localCommit` is ahead of and behind `upstreamCommit`, in that order.
    public func graphAheadBehind(localCommit: Commit, upstreamCommit: Commit) -> Result<(Int, Int), NSError> {
        let aheadPointer = UnsafeMutablePointer<Int>.allocate(capacity: 1)
        let behindPointer = UnsafeMutablePointer<Int>.allocate(capacity: 1)
        var oid = localCommit.oid.oid
        var rOid = upstreamCommit.oid.oid
        let result = git_graph_ahead_behind(aheadPointer, behindPointer, pointer, &oid, &rOid)
        guard result == GIT_OK.rawValue else {
            return Result.failure(NSError(gitError: result, pointOfFailure: "git_merge_analysis"))
        }

        return .success((aheadPointer.pointee, behindPointer.pointee))
    }
}

extension Array {
    fileprivate func aggregateResult<Value, Error>() -> Result<[Value], Error> where Element == Result<
        Value,
        Error
    > {
        var values: [Value] = []
        for result in self {
            switch result {
            case let .success(value):
                values.append(value)
            case let .failure(error):
                return .failure(error)
            }
        }
        return .success(values)
    }
}

func resolveUrl(
    urlResolved _: UnsafeMutablePointer<OpaquePointer?>,
    url _: UnsafePointer<CChar>,
    payload _: UnsafeMutableRawPointer
) -> Int32 {
    GIT_OK.rawValue
}

// swiftlint:enable file_length
